//! TEST-2.a — Migration up/down round-trip harness.
//!
//! For every `NNNN/` migration directory under `src-tauri/migrations/`, this
//! test applies the up SQL to a fresh SQLite database that already contains
//! the cumulative state of all *prior* migrations, captures a normalized
//! snapshot of `sqlite_master`, then applies the matching `NNNN_down/` SQL
//! and asserts that the post-down snapshot equals the pre-up snapshot.
//!
//! A migration whose `NNNN_down/` directory contains a `.noop_down` marker
//! file is exempt from the round-trip check — the harness emits a warning to
//! stderr and continues. Marking those directories is deliberately *not* done
//! in this PR; that is TEST-2.b (issue #87, blocked on this).
//!
//! Round-trip failures are collected and reported together at the end of the
//! test so a reviewer can see every offender in one CI log, rather than the
//! test halting at the first regression.
//!
//! Conventions used here:
//! * Migrations are loaded relative to `CARGO_MANIFEST_DIR` so the test does
//!   not depend on the cwd.
//! * Each `.sql` file in a migration directory is applied (in name order) as
//!   a single `execute_batch`, mirroring the way `tauri-plugin-sql` runs
//!   them at app startup via the `concat!(include_str!(...), ...)` blocks
//!   in `src-tauri/src/lib.rs`.
//! * Snapshot query: `SELECT type, name, tbl_name, sql FROM sqlite_master
//!   WHERE type IN ('table','index','trigger','view') AND name NOT LIKE
//!   'sqlite_%' ORDER BY type, name`. `sqlite_%` rows are autogenerated
//!   (e.g. internal indexes for `INTEGER PRIMARY KEY AUTOINCREMENT`) and are
//!   not authored by migrations.

use std::fs;
use std::path::{Path, PathBuf};

use rusqlite::Connection;

/// One row of the normalized `sqlite_master` snapshot.
#[derive(Debug, Clone, PartialEq, Eq)]
struct SchemaRow {
    obj_type: String,
    name: String,
    tbl_name: String,
    sql: Option<String>,
}

/// A discovered up/down migration pair.
#[derive(Debug)]
struct MigrationPair {
    /// Stem of the up directory, e.g. `"0001"`.
    id: String,
    up_dir: PathBuf,
    down_dir: PathBuf,
}

fn migrations_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("migrations")
}

/// Discover every `NNNN/` migration directory paired with its `NNNN_down/`
/// counterpart. Sorted by the numeric stem so the cumulative replay is in
/// migration order.
fn discover_migrations() -> Vec<MigrationPair> {
    let root = migrations_dir();
    let mut pairs: Vec<MigrationPair> = Vec::new();

    let entries =
        fs::read_dir(&root).unwrap_or_else(|e| panic!("read_dir {}: {e}", root.display()));

    for entry in entries {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let name = match path.file_name().and_then(|n| n.to_str()) {
            Some(n) => n.to_string(),
            None => continue,
        };
        // We want the up directories — those without the `_down` suffix.
        if name.ends_with("_down") {
            continue;
        }
        let down_dir = root.join(format!("{name}_down"));
        if !down_dir.is_dir() {
            panic!(
                "migration {name} has no matching {name}_down/ directory \
                 (CLAUDE.md: \"Always create a rollback migration\")"
            );
        }
        pairs.push(MigrationPair {
            id: name,
            up_dir: path,
            down_dir,
        });
    }

    pairs.sort_by(|a, b| a.id.cmp(&b.id));
    pairs
}

/// Read every `*.sql` file in `dir` (sorted by file name) and concatenate
/// them with newline separators, matching the order used by the runtime
/// `concat!(include_str!(...))` blocks in `src-tauri/src/lib.rs`.
fn collect_sql(dir: &Path) -> String {
    let mut files: Vec<PathBuf> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("read_dir {}: {e}", dir.display()))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().and_then(|x| x.to_str()) == Some("sql"))
        .collect();
    files.sort();

    let mut out = String::new();
    for f in files {
        let body = fs::read_to_string(&f).unwrap_or_else(|e| panic!("read {}: {e}", f.display()));
        out.push_str(&body);
        if !body.ends_with('\n') {
            out.push('\n');
        }
    }
    out
}

/// Apply every `.sql` file in `dir` as a single `execute_batch` against
/// `conn`. Returns the SQL that was applied (helpful for failure messages).
fn apply_dir(conn: &Connection, dir: &Path) -> rusqlite::Result<String> {
    let sql = collect_sql(dir);
    conn.execute_batch(&sql)?;
    Ok(sql)
}

/// Capture the normalized `sqlite_master` snapshot ordered by (type, name).
fn snapshot(conn: &Connection) -> rusqlite::Result<Vec<SchemaRow>> {
    let mut stmt = conn.prepare(
        "SELECT type, name, tbl_name, sql \
         FROM sqlite_master \
         WHERE type IN ('table','index','trigger','view') \
           AND name NOT LIKE 'sqlite_%' \
         ORDER BY type, name",
    )?;
    let rows = stmt
        .query_map([], |row| {
            Ok(SchemaRow {
                obj_type: row.get(0)?,
                name: row.get(1)?,
                tbl_name: row.get(2)?,
                sql: row.get(3)?,
            })
        })?
        .collect::<rusqlite::Result<Vec<_>>>()?;
    Ok(rows)
}

/// Render a snapshot as a human-diffable multi-line string for failure
/// reporting.
fn render_snapshot(rows: &[SchemaRow]) -> String {
    let mut s = String::new();
    for r in rows {
        s.push_str(&format!(
            "[{:<7}] {} (tbl={})\n  sql: {}\n",
            r.obj_type,
            r.name,
            r.tbl_name,
            r.sql.as_deref().unwrap_or("<none>"),
        ));
    }
    s
}

/// Compute the symmetric difference between two snapshots. Returned as
/// `(only_in_before, only_in_after)` for clear failure messages.
fn diff_snapshots(before: &[SchemaRow], after: &[SchemaRow]) -> (Vec<SchemaRow>, Vec<SchemaRow>) {
    let only_before: Vec<SchemaRow> = before
        .iter()
        .filter(|r| !after.contains(r))
        .cloned()
        .collect();
    let only_after: Vec<SchemaRow> = after
        .iter()
        .filter(|r| !before.contains(r))
        .cloned()
        .collect();
    (only_before, only_after)
}

#[test]
fn migration_round_trip() {
    let pairs = discover_migrations();
    assert!(
        !pairs.is_empty(),
        "no migrations discovered under {} — fix the test, not the codebase",
        migrations_dir().display()
    );

    let mut failures: Vec<String> = Vec::new();
    let mut skipped: Vec<String> = Vec::new();

    for (idx, pair) in pairs.iter().enumerate() {
        // `.noop_down` opt-out marker (TEST-2.b will populate these).
        let noop_marker = pair.down_dir.join(".noop_down");
        if noop_marker.exists() {
            eprintln!(
                "WARN: skipping round-trip for migration {} \
                 (down marked as no-op via {})",
                pair.id,
                noop_marker.display()
            );
            skipped.push(pair.id.clone());
            continue;
        }

        // Fresh in-memory DB per case. Foreign keys ON to match the runtime
        // pragma in `0001/00_pragma.sql`; some down migrations toggle this
        // around table rebuilds and assume it is on.
        let conn = Connection::open_in_memory().expect("open in-memory sqlite");
        conn.execute_batch("PRAGMA foreign_keys = ON;")
            .expect("enable FKs");

        // Replay every prior migration up-only so `pair` runs against the
        // cumulative schema state it expects in production.
        for prior in &pairs[..idx] {
            if let Err(e) = apply_dir(&conn, &prior.up_dir) {
                panic!(
                    "failed to replay prior up migration {} while \
                     preparing round-trip for {}: {e}",
                    prior.id, pair.id
                );
            }
        }

        // Pre-up snapshot.
        let before = match snapshot(&conn) {
            Ok(s) => s,
            Err(e) => panic!("snapshot before {} failed: {e}", pair.id),
        };

        // Apply up.
        if let Err(e) = apply_dir(&conn, &pair.up_dir) {
            failures.push(format!("[{}] up SQL failed to apply: {e}", pair.id));
            continue;
        }

        // Apply down.
        if let Err(e) = apply_dir(&conn, &pair.down_dir) {
            failures.push(format!("[{}] down SQL failed to apply: {e}", pair.id));
            continue;
        }

        // Post-down snapshot.
        let after = match snapshot(&conn) {
            Ok(s) => s,
            Err(e) => {
                failures.push(format!("[{}] snapshot after down failed: {e}", pair.id));
                continue;
            }
        };

        if before != after {
            let (only_before, only_after) = diff_snapshots(&before, &after);
            failures.push(format!(
                "[{}] schema drift after up/down round-trip\n\
                 -- only in pre-up snapshot ({} rows) --\n{}\
                 -- only in post-down snapshot ({} rows) --\n{}\
                 hint: either fix the down migration so it exactly inverts \
                 the up migration, or — if SQLite genuinely cannot invert \
                 it (e.g. column drops on older SQLite, side-effecting \
                 UPDATEs that touch keyring-backed data) — create the \
                 marker file `migrations/{}_down/.noop_down` so this \
                 harness skips the pair (TEST-2.b will land those markers).",
                pair.id,
                only_before.len(),
                render_snapshot(&only_before),
                only_after.len(),
                render_snapshot(&only_after),
                pair.id,
            ));
        }
    }

    if !skipped.is_empty() {
        eprintln!(
            "migration_round_trip: skipped {} no-op-marked migration(s): {}",
            skipped.len(),
            skipped.join(", ")
        );
    }

    if !failures.is_empty() {
        let header = format!("{} migration round-trip failure(s):\n", failures.len());
        panic!("{}{}", header, failures.join("\n\n"));
    }
}
